#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;
use MS::Parser::PepXML;

my $total = 0;
my $n_lab = 0;

my $fn = $ARGV[0];

my $p = MS::Parser::PepXML->new;
$p->load($fn);
while (my $scan = $p->next_query) {
    ++$total;
    my $n_mod = $scan->{results}->[0]->{hits}->[0]->{mods}->{mod_nterm_mass};
    ++$n_lab if (defined $n_mod && $n_mod eq '230.170757');
}
my $efficiency = sprintf "%.2f", $n_lab/$total;
warn "$n_lab of $total\n";
print "$efficiency\t$fn\n";

